saml_metadata:
  path:     /saml/metadata
  defaults: { _controller: Angle\OneLoginAzureSamlBundle\Controller\SamlController::metadata }

saml_acs:
  path:     /saml/acs
  methods:  ['POST']
  defaults: { _controller: Angle\OneLoginAzureSamlBundle\Controller\SamlController::assertionConsumerService }

saml_login:
  path:     /saml/login
  defaults: { _controller: Angle\OneLoginAzureSamlBundle\Controller\SamlController::login }

saml_logout:
  path:     /saml/logout
  defaults: { _controller: Angle\OneLoginAzureSamlBundle\Controller\SamlController::singleLogoutService }